server {
    server_name novaventanasypuertas.com www.novaventanasypuertas.com novaventanasypuertas.es www.novaventanasypuertas.es;
    root /var/www/nova-ventanas-y-puertas/browser;
    index index.html;

    include /etc/nginx/mime.types;
    types {
        application/javascript mjs;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/novaventanasypuertas.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/novaventanasypuertas.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    listen 80;
    listen [::]:80;
    server_name novaventanasypuertas.com www.novaventanasypuertas.com novaventanasypuertas.es www.novaventanasypuertas.es;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://novaventanasypuertas.com$request_uri;
    }
}